# Generated by Django 6.0.1 on 2026-01-19 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_tasks_delete_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
